### ISSUE TITLE
The navigation links container has an incorrect indent on the right

### ISSUE THREAD

**Issue by vladimirfriptu** [vladimirfriptu/business_landing_liana#2]
Контейнер с ссылками навигации имеет лишний отступ справа, его нужно убрать. То есть последняя ссылка не должна иметь margin-right

<img width="2112" alt="Снимок экрана 2024-02-27 в 10 22 04" src="https://github.com/vladimirfriptu/business_landing_liana/assets/35306151/22fcbf25-4189-4876-857a-c7eeb4820b85">

**Comment by Gulfakse** [comment]
пофиксила
